#ifndef RVARAGO_ABSENT_BIND_H
#define RVARAGO_ABSENT_BIND_H

#include <functional>

#include "absent/support/member.h"

namespace rvarago::absent {

/***
 * Given a nullable type N<A> (i.e. optional-like object), and an unary function f: A -> N<B>:
 * - When empty: it should return a new empty nullable N<B>.
 * - When *not* empty: it should return a nullable N<B> generated by applying the unary mapping function to the input
 * nullable's value, already wrapped in a nullable N<B>.
 *
 * @param input a nullable N<A>.
 * @param mapper an unary function A -> N<B>.
 * @return a new nullable generated by mapper, possibly empty if input was also empty.
 */
template <template <typename> typename Nullable, typename UnaryFunction, typename A>
constexpr auto bind(Nullable<A> const &input, UnaryFunction mapper) noexcept -> decltype(mapper(std::declval<A>())) {
    using NullableB = decltype(mapper(std::declval<A>()));
    if (!input) {
        return NullableB{};
    }
    return mapper(*input);
}

/***
 * Infix version of bind.
 */
template <template <typename> typename Nullable, typename UnaryFunction, typename A>
constexpr auto operator>>(Nullable<A> const &input, UnaryFunction mapper) noexcept
    -> decltype(mapper(std::declval<A>())) {
    return bind(input, mapper);
}

/***
 * The same as bind but for a member function that has to be const and parameterless.
 */
template <template <typename> typename Nullable, typename A, typename B>
constexpr auto bind(Nullable<A> const &input, support::member_mapper<const A, Nullable<B>> mapper) noexcept
    -> Nullable<B> {
    return bind(input, [&mapper](auto const &value) { return std::invoke(mapper, value); });
}

/***
 * Infix version of bind for a member function.
 */
template <template <typename> typename Nullable, typename A, typename B>
constexpr auto operator>>(Nullable<A> const &input, support::member_mapper<const A, Nullable<B>> mapper) noexcept
    -> Nullable<B> {
    return bind(input, mapper);
}

}

#endif
